baseURL = 'https://blog.reciperadar.com'
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
languageCode = 'en-us'
theme = 'hugo-flex'
title = 'RecipeRadar Blog'

[menu]
main = [
  {name = 'Posts', pageRef = '/post', weight = 2},
  {name = 'Tags', pageRef = '/tags', weight = 3},
  {name = 'RSS', pageRef = '/', weight = 5, params = [ {format = 'rss'} ] }
]

[params]
math = false
color = '#005'

[frontmatter]
date = ['date', ':git']

[languages]
  [languages.en]
    languageName = 'English'
    title = 'RecipeRadar Blog'

    [languages.en.params]
      description = 'News and articles relating to the RecipeRadar search engine'
      footer = '&copy; 2019 <a href="https://find-and-update.company-information.service.gov.uk/company/SC647817">OpenCulinary C.I.C.</a>'

    [languages.en.params.logo]
      logoText = 'RecipeRadar Blog'
      logoHomeLink = '/'

[pagination]
pagerSize = 3
