baseURL = 'https://blog.reciperadar.com'
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
languageCode = 'en-us'
theme = 'primer'
title = 'RecipeRadar Blog'

[params]
math = false
themeColor = 'blue'
fullWidthTheme = false
centerTheme = false

[frontmatter]
date = ['date', ':git']

[languages]
  [languages.en]
    languageName = 'English'
    title = 'RecipeRadar Blog'
    copyright = '&copy; 2019 [OpenCulinary C.I.C.](https://find-and-update.company-information.service.gov.uk/company/SC647817)'

    [languages.en.params]
      subtitle = 'News and articles relating to the RecipeRadar search engine'
      keywords = 'recipes, software, news, technology'
      menuMore = 'Show more'
      readMore = 'Read more'
      readOtherPosts = 'Read other posts'

    [languages.en.params.logo]
      logoText = 'RecipeRadar Blog'
      logoHomeLink = '/'
