baseURL = 'https://blog.reciperadar.com'
enableGitInfo = true
enableRobotsTXT = true
disableHugoGeneratorInject = true
languageCode = 'en-us'
theme = 'primer'
title = 'RecipeRadar Blog'

[params]
themeColor = 'blue'
fullWidthTheme = false
centerTheme = false

[frontmatter]
date = ['date', ':git']

[languages]
  [languages.en]
    languageName = 'English'
    title = 'RecipeRadar Blog'
    subtitle = 'News and articles relating to the RecipeRadar search engine'
    keywords = 'recipes, software, news, technology'
    copyright = '&copy; RecipeRadar'
    menuMore = 'Show more'
    readMore = 'Read more'
    readOtherPosts = 'Read other posts'

    [languages.en.params.logo]
      logoText = 'RecipeRadar Blog'
      logoHomeLink = '/'
