baseURL = "https://blog.reciperadar.com"
enableGitInfo = true
languageCode = "en-us"
theme = "terminal"
title = "RecipeRadar Engineering"

[params]
themeColor = "blue"
fullWidthTheme = false
centerTheme = false

[frontmatter]
date = [":git"]

[languages]
  [languages.en]
    languageName = "English"
    title = "RecipeRadar Engineering"
    subtitle = "The technology behind the recipe search engine"
    keywords = "recipes, software, engineering, technology"
    copyright = "&copy; RecipeRadar"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "RecipeRadar Engineering"
      logoHomeLink = "/"
