apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
      role: web
  template:
    metadata:
      labels:
        app: blog
        role: web
    spec:
      containers:
      - image: registry.openculinary.org/reciperadar/blog
        imagePullPolicy: IfNotPresent
        name: blog
        ports:
        - containerPort: 80
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /var/cache/nginx
          name: var-cache-nginx
      volumes:
      - name: var-run
        emptyDir:
          medium: "Memory"
          sizeLimit: "4Mi"
      - name: var-cache-nginx
        emptyDir:
          medium: "Memory"
          sizeLimit: "128Mi"
