apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
spec:
  rules:
  - host: blog
    http:
      paths:
      - backend:
          serviceName: blog-service
          servicePort: 80
